on:
    push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build-wheels:
    uses: ./.github/workflows/python_build.yml
    secrets: inherit

  publish:
    needs: build-wheels
    if: github.repository == 'qperfect-io/qleo'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v4 # clone current repo into runner
      with:
        name: qleo_wheels
        path: qleo_wheels

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qleo_wheels/.
        password: ${{ secrets.PYPI_API_TOKEN }}